/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package store_billing;

import Buslogic.clsbil;
import Buslogic.clsbildet;
import Buslogic.clsbildetprp;
import Buslogic.clsbilprp;
import Buslogic.clsmed;
import Buslogic.clsmedprp;
import Buslogic.clsstk;
import Buslogic.clsstkprp;
import Buslogic.clstmpbil;
import java.awt.event.ItemEvent;
import java.util.Date;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author csgroup
 */
public class frmbil extends javax.swing.JInternalFrame {

    /**
     * Creates new form frmbil
     */
    List<clsmedprp> k;
    public frmbil() {
        initComponents();
        DefaultComboBoxModel mod=(DefaultComboBoxModel)
                cmbmed.getModel();
        clsmed obj=new clsmed();
        k=obj.disp_rec();
        for(clsmedprp p:k)
        {
            mod.addElement(p.getmednam());
        }
        cmbmed.setModel(mod);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtcstnam = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtphn = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cmbmed = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        txtqty = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();

        setClosable(true);
        setTitle("Bill");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setText("Customer Name");

        jLabel2.setText("Phone No");

        jLabel3.setText("Select Medicine");

        cmbmed.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbmedItemStateChanged(evt);
            }
        });
        cmbmed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbmedActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Stock Code", "Mnf Date", "Exp Date", "Quantity", "Price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel4.setText("Enter Quantity To Purchase");

        jButton1.setText("Add To Bill");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Medicine", "Quantity", "Price", "Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable2);

        jButton2.setText("Generate Bill");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 539, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtcstnam)
                                    .addComponent(cmbmed, 0, 180, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(txtphn, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(txtqty, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane2)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(200, 200, 200)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtcstnam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(txtphn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cmbmed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtqty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbmedItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbmedItemStateChanged
        // TODO add your handling code here:
        if(evt.getStateChange()==ItemEvent.SELECTED)
        {
   int mcod=k.get(cmbmed.getSelectedIndex()).getmedcod();
            clsstk obj=new clsstk();
   List<clsstkprp> k=obj.dspmedstk(mcod);
   DefaultTableModel mod=(DefaultTableModel)jTable1.getModel();
   mod.setRowCount(0);
   for(clsstkprp p:k)
   {
       if(p.getstkqty()>0)
       {
           Object[] rowdata=new Object[5];
           rowdata[0]=p.getstkcod();
           rowdata[1]=p.getstkmnfdat();
           rowdata[2]=p.getstkexpdat();
           rowdata[3]=p.getstkqty();
           rowdata[4]=p.getstkprc();
           mod.addRow(rowdata);
       }
   }
   jTable1.setModel(mod);
        }
    }//GEN-LAST:event_cmbmedItemStateChanged

    private void cmbmedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbmedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbmedActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if(jTable1.getSelectedRow()==-1)
  JOptionPane.showMessageDialog(this,"Please select stock from which you want to purchase");
        else
        {
           if(Integer.parseInt(txtqty.getText())>
                   (int)jTable1.getValueAt(jTable1.
                           getSelectedRow(),3))
           {
  JOptionPane.showMessageDialog(this,"Quantity low in stock selected");
           }
           else
           {
               clstmpbil obj=new clstmpbil();
               obj.setQtypur(Integer.parseInt(txtqty.getText()));
               obj.setMednam(cmbmed.getSelectedItem().toString());
               obj.setMedcod(k.get(cmbmed.getSelectedIndex())
                       .getmedcod());
               obj.setStkcod((int)jTable1.getValueAt
        (jTable1.getSelectedRow(), 0));
               obj.setPrc((float)jTable1.getValueAt
        (jTable1.getSelectedRow(),4));
               clstmpbil.arr.add(obj);
            loadbill();   
               
           }
        }
    }//GEN-LAST:event_jButton1ActionPerformed
private void clear()
{
    
}
    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        // TODO add your handling code here:
      if(jTable2.getSelectedRow()!=-1)
      {
          clstmpbil.arr.remove(jTable2.getSelectedRow());
      }
      loadbill();
    }//GEN-LAST:event_jTable2MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       clsbil obj=new clsbil();
       clsbilprp objprp=new clsbilprp();
       objprp.setbilcstnam(txtcstnam.getText());
       objprp.setbilcstphn(txtphn.getText());
       objprp.setbildat(new Date());
       int bilcod=obj.save_rec(objprp);
        clsbildet obj1=new clsbildet();
        clsbildetprp objprp1=new clsbildetprp();
        for(clstmpbil t:clstmpbil.arr)
        {
            objprp1.setbildetbilcod(bilcod);
            objprp1.setbildetqty(t.getQtypur());
            objprp1.setbildetstkcod(t.getStkcod());
            obj1.save_rec(objprp1);
        }
        clstmpbil.arr.clear();
        JOptionPane.showMessageDialog(this,"Bill Generated with Bill No "+bilcod);
        clear();
    }//GEN-LAST:event_jButton2ActionPerformed
 private void loadbill()
 {
     DefaultTableModel mod=(DefaultTableModel)jTable2
             .getModel();
     mod.setRowCount(0);
     for(clstmpbil t:clstmpbil.arr)
     {
         Object[] rowdata=new Object[4];
         rowdata[0]=t.getMednam();
         rowdata[1]=t.getQtypur();
         rowdata[2]=t.getPrc();
         rowdata[3]=t.getQtypur()*t.getPrc();
         mod.addRow(rowdata);
     }
     jTable2.setModel(mod);
 }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbmed;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField txtcstnam;
    private javax.swing.JTextField txtphn;
    private javax.swing.JTextField txtqty;
    // End of variables declaration//GEN-END:variables
}
