/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package store_billing;

import Buslogic.clsmed;
import Buslogic.clsmedprp;
import Buslogic.clsstk;
import Buslogic.clsstkprp;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.DateFormatter;
import javax.swing.text.DefaultFormatterFactory;

/**
 *
 * @author csgroup
 */
public class frmstk extends javax.swing.JInternalFrame {

    /**
     * Creates new form frmstk
     */
    List<clsmedprp> k;
    public frmstk() {
        initComponents();
          DateFormat format = new SimpleDateFormat("dd/MM/yyyy");
        DateFormatter df = new DateFormatter(format);
        
         txtmfgdat.setFormatterFactory(new DefaultFormatterFactory(df));
         txtexpdat.setFormatterFactory(new DefaultFormatterFactory(df));
        DefaultComboBoxModel mod=(DefaultComboBoxModel)
                cmbmed.getModel();
        clsmed obj=new clsmed();
        k=obj.disp_rec();
        for(clsmedprp p:k)
        {
            mod.addElement(p.getmednam());
        }
        cmbmed.setModel(mod);
        setClosable(true);
        setLocation(100, 100);
        clear();
        loaddata();
        jButton2.setEnabled(false);
        jButton4.setEnabled(false);
    }
public void clear()
{
    txtprc.setText("");
    txtqty.setText("");
    txtmfgdat.setText("");
    txtexpdat.setText("");
}
    
public void loaddata()
{
//    clsstk obj=new clsstk();
//    List<clsstkprp> k=obj.disp_rec();
//    DefaultTableModel mod=(DefaultTableModel)jTable2.getModel();
//    mod.setRowCount(0);
//    for(clsstkprp p:k)
//    {
//        Object[] rowdata=new Object[5];
//        rowdata[0]=p.getstkcod();
//        rowdata[1]=p.getstkqty();
//        rowdata[2]=p.getstkprc();
//        rowdata[3]=p.getstkmnfdat();
//        rowdata[4]=p.getstkexpdat();
//        mod.addRow(rowdata);
//    }
//    jTable2.setModel(mod);
//    
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cmbmed = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        txtprc = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtqty = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtmfgdat = new javax.swing.JFormattedTextField();
        jLabel5 = new javax.swing.JLabel();
        txtexpdat = new javax.swing.JFormattedTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setTitle("Manage Stock");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setText("Select Medicine");

        cmbmed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbmedActionPerformed(evt);
            }
        });

        jLabel2.setText("Price");

        jLabel3.setText("Quantity");

        jLabel4.setText("Mfg. Date");

        jLabel5.setText("Exp. Date");

        jButton1.setText("Save");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Delete");

        jButton3.setText("Cancel");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Update");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtmfgdat, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel1)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addGap(32, 32, 32)
                                    .addComponent(txtprc, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addComponent(jButton4)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(cmbmed, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtqty)
                            .addComponent(txtexpdat, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(62, 62, 62)))
                .addGap(90, 90, 90))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cmbmed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtprc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(txtqty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtmfgdat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(txtexpdat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton4))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Stock Code", "Quentity", "Price", "Manufacturing Date", "Expiry Date"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 645, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 645, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(166, 166, 166))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       if(txtprc.getText()==""||txtqty.getText()==""
               ||txtmfgdat.getText()==""||txtexpdat.getText()=="")
           JOptionPane.showMessageDialog(this,"Please Fill Entries");
       else
       {
           try {
               clsstk obj=new clsstk();
               clsstkprp objprp=new clsstkprp();
               objprp.setstkprc(Float.parseFloat(txtprc.getText()));
               objprp.setstkqty(Integer.parseInt(txtqty.getText()));
               objprp.setstkdat(new Date());
               objprp.setstkmedcod(k.get
                        (cmbmed.getSelectedIndex()).getmedcod());
               Date mfgdat=new SimpleDateFormat("dd/MM/yyyy").parse(txtmfgdat.getText());
               Date expdat=new SimpleDateFormat("dd/MM/yyyy").parse(txtexpdat.getText());
               objprp.setstkmnfdat(mfgdat);
               objprp.setstkexpdat(expdat);
               obj.save_rec(objprp);
           } catch (ParseException ex) {
               Logger.getLogger(frmstk.class.getName()).log(Level.SEVERE, null, ex);
           }
     loaddata();
       }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cmbmedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbmedActionPerformed
       int a=k.get(cmbmed.getSelectedIndex()).getmedcod();
        
        clsstk obj=new clsstk();
    List<clsstkprp> k=obj.disp_rec(a);
    DefaultTableModel mod=(DefaultTableModel)jTable2.getModel();
    mod.setRowCount(0);
    for(clsstkprp p:k)
    {
        Object[] rowdata=new Object[5];
        rowdata[0]=p.getstkcod();
        rowdata[1]=p.getstkqty();
        rowdata[2]=p.getstkprc();
        rowdata[3]=p.getstkmnfdat();
        rowdata[4]=p.getstkexpdat();
        mod.addRow(rowdata);
    }
    jTable2.setModel(mod);
        
    }//GEN-LAST:event_cmbmedActionPerformed
int scod;
    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        int idx=jTable2.getSelectedRow();
      scod=(int)jTable2.getValueAt(idx, 0);
       clsstk obj1=new clsstk();
      clsstkprp p1=obj1.find_rec(scod);
      clsmed obj=new clsmed();
      clsmedprp p=obj.find_rec(p1.getstkmedcod());
      txtprc.setText(jTable2.getValueAt(idx, 2).toString());
      txtqty.setText(jTable2.getValueAt(idx, 1).toString());
      txtmfgdat.setText(jTable2.getValueAt(idx, 3).toString());
      txtexpdat.setText(jTable2.getValueAt(idx, 4).toString());
     
      cmbmed.setSelectedItem(p.getmednam());
      
        jButton2.setEnabled(true);
        jButton4.setEnabled(true);
    }//GEN-LAST:event_jTable2MouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        clear();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        
        if(txtprc.getText().equals("") || 
              txtqty.getText().equals("") ||
              txtmfgdat.getText().equals("") ||  txtexpdat.getText().equals(""))
      JOptionPane.showMessageDialog(this,"Please fill entries");
      else  
      {
           try {
      
          clsstkprp objprp=new clsstkprp();
          clsstk obj=new clsstk();
           objprp.setstkprc(Float.parseFloat(txtprc.getText()));
               objprp.setstkqty(Integer.parseInt(txtqty.getText()));
               objprp.setstkdat(new Date());
               objprp.setstkmedcod(k.get
                        (cmbmed.getSelectedIndex()).getmedcod());
               Date mfgdat=new SimpleDateFormat("dd/MM/yyyy").parse(txtmfgdat.getText());
               Date expdat=new SimpleDateFormat("dd/MM/yyyy").parse(txtexpdat.getText());
               objprp.setstkmnfdat(mfgdat);
               objprp.setstkexpdat(expdat);
     objprp.setstkcod(scod);
          obj.upd_rec(objprp);
        jButton2.setEnabled(false);
        jButton4.setEnabled(false);
        } catch (ParseException ex) {
               Logger.getLogger(frmstk.class.getName()).log(Level.SEVERE, null, ex);
           }
      }
    }//GEN-LAST:event_jButton4ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbmed;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JFormattedTextField txtexpdat;
    private javax.swing.JFormattedTextField txtmfgdat;
    private javax.swing.JTextField txtprc;
    private javax.swing.JTextField txtqty;
    // End of variables declaration//GEN-END:variables
}
